
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[XPAR_XIIC_NUM_INSTANCES] =
{
	{
		XPAR_FMC_IMAGEON_IIC_0_DEVICE_ID,
		XPAR_FMC_IMAGEON_IIC_0_BASEADDR,
		XPAR_FMC_IMAGEON_IIC_0_TEN_BIT_ADR,
		XPAR_FMC_IMAGEON_IIC_0_GPO_WIDTH
	},
	{
		XPAR_FMC_IPMI_ID_EEPROM_0_DEVICE_ID,
		XPAR_FMC_IPMI_ID_EEPROM_0_BASEADDR,
		XPAR_FMC_IPMI_ID_EEPROM_0_TEN_BIT_ADR,
		XPAR_FMC_IPMI_ID_EEPROM_0_GPO_WIDTH
	}
};


