// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Live(
	blockSize int,
	maxDisparity int,
) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container mx-auto px-4 grid grid-cols-1 lg:grid-cols-4 gap-6\"><div class=\"lg:col-span-3 space-y-6\"><div class=\"bg-gray-800 rounded-lg shadow-lg p-4\"><div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\"><div class=\"flex flex-col items-center\"><h2 class=\"text-xl font-semibold text-gray-200 mb-2\">Left Camera</h2><div id=\"left-camera-feed\" class=\"w-full h-64 bg-black rounded-lg overflow-hidden relative\"><div class=\"absolute inset-0 flex items-center justify-center text-gray-500\" hx-ws-connect=\"/wsl\">Waiting for connection...</div></div></div><div class=\"flex flex-col items-center\"><h2 class=\"text-xl font-semibold text-gray-200 mb-2\">Right Camera</h2><div id=\"right-camera-feed\" class=\"w-full h-64 bg-black rounded-lg overflow-hidden relative\"><div class=\"absolute inset-0 flex items-center justify-center text-gray-500\" hx-ws-connect=\"/wsr\">Waiting for connection...</div></div></div></div></div><div class=\"bg-gray-800 rounded-lg shadow-lg p-4\"><h2 class=\"text-xl font-semibold text-gray-200 mb-2 text-center\">Depth Map</h2><div id=\"depth-map-image\" class=\"w-full h-64 bg-black rounded-lg overflow-hidden relative\"><div class=\"absolute inset-0 flex items-center justify-center text-gray-500\">No depth map available</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Control(blockSize, maxDisparity).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = status().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
